POST https://thetamiddleware.herokuapp.com/addSeed/
Content-Type: application/json

{
"id": "IDalpha",
"pass": "PASSWORD",
"info": "HJHJFJGHFHGFHJ"
}

###
POST https://thetamiddleware.herokuapp.com/sendTx/
Content-Type: application/json

{
"seed": "VLLPIQLDNUXPF9ECVNDQTDQITIQBSTNWJPXSHWEMHSDYHOEZT9CMMRKOIFRZPSJVDBZGJOYMXM9KPJAPY",
"address": "LZK9VJPEJNKHKNADMKYIQVBLWRW9YEXBDPGSYMONHFGVXDHQ9FRLPDPCCHNYAJRCQSJWKWHBFHKYNPCHA",
"msg": "Sending through Express Server"
}

###
POST https://thetamiddleware.herokuapp.com/updateAddressInfo/
Content-Type: application/json

{
"seed": "VLLPIQLDNUXPF9ECVNDQTDQITIQBSTNWJPXSHWEMHSDYHOEZT9CMMRKOIFRZPSJVDBZGJOYMXM9KPJAPY",
"address": "LZK9VJPEJNKHKNADMKYIQVBLWRW9YEXBDPGSYMONHFGVXDHQ9FRLPDPCCHNYAJRCQSJWKWHBFHKYNPCHA",
"info": "Updated through Express Server"
}


###

POST https://thetamiddleware.herokuapp.com/addAddress/
Content-Type: application/json

{
    "seed":"VLLPIQLDNUXPF9ECVNDQTDQITIQBSTNWJPXSHWEMHSDYHOEZT9CMMRKOIFRZPSJVDBZGJOYMXM9KPJAPY",
    "deviceNum": 5,
    "secLevel": 3,
    "id": "IDalpha",
    "password": "PASSWORD",
    "info": "HJHJFJGHFHGFHJ"
}


###

GET https://thetamiddleware.herokuapp.com/getSeed/Username2&Password2


###
GET https://thetamiddleware.herokuapp.com/getAllSeeds/Admin_ID&Admin_Password

###
GET https://thetamiddleware.herokuapp.com/getSeed/Username2&Password2

###
GET https://thetamiddleware.herokuapp.com/forgotPassword/MBNDML9YVMXWKOMQZKYNJZQQRIQUQYLSNNDLSHCEAKKDJYHBPEWXBNXNXWOGQTHYUCBPPECYHVQFTZFOQ

###
GET https://thetamiddleware.herokuapp.com/getTx/JKDXTRKXTILUCZCYERXMZCXKGBQWDIZYLLWFYKCYAMAVBXBAC9OKBVQVLRXHATUVDSNMVJK9IYHTA9999

###
GET https://thetamiddleware.herokuapp.com/getHash/LZK9VJPEJNKHKNADMKYIQVBLWRW9YEXBDPGSYMONHFGVXDHQ9FRLPDPCCHNYAJRCQSJWKWHBFHKYNPCHA&21:42:22/28-8-2020

###
GET https://thetamiddleware.herokuapp.com/getAllAddresses/MBNDML9YVMXWKOMQZKYNJZQQRIQUQYLSNNDLSHCEAKKDJYHBPEWXBNXNXWOGQTHYUCBPPECYHVQFTZFOQ

###
GET https://thetamiddleware.herokuapp.com/getAllHash/TWAHITQOTATJPIBSSWPON9ISYOOZJCWWUOEEASVZMTWKCKSWKQSDMUTGOFO9JBEYWJGOVBCIS9BJR9HFD&29-10-2020

###
GET https://thetamiddleware.herokuapp.com/getLastTx/TWAHITQOTATJPIBSSWPON9ISYOOZJCWWUOEEASVZMTWKCKSWKQSDMUTGOFO9JBEYWJGOVBCIS9BJR9HFD

###
GET https://thetamiddleware.herokuapp.com/getMAM/MBNDML9YVMXWKOMQZKYNJZQQRIQUQYLSNNDLSHCEAKKDJYHBPEWXBNXNXWOGQTHYUCBPPECYHVQFTZFOQ&NTWSWV9CBWVKZXKLWSOHFLCJTDWIAMVSYRD9DFDXWJWFBVPWYUYDJQDOOLEWLPOAPHR9CHQKTMEOYRKDC