POST http://localhost:5000/addSeed/
Content-Type: application/json

{
"id": "IDalpha",
"pass": "PASSWORD",
"info": "HJHJFJGHFHGFHJ"
}

###
POST http://localhost:5000/sendTx/
Content-Type: application/json

{
"seed": "VLLPIQLDNUXPF9ECVNDQTDQITIQBSTNWJPXSHWEMHSDYHOEZT9CMMRKOIFRZPSJVDBZGJOYMXM9KPJAPY",
"address": "LZK9VJPEJNKHKNADMKYIQVBLWRW9YEXBDPGSYMONHFGVXDHQ9FRLPDPCCHNYAJRCQSJWKWHBFHKYNPCHA",
"msg": "Sending through Express Server"
}

###
POST http://localhost:5000/updateAddressInfo/
Content-Type: application/json

{
"seed": "VLLPIQLDNUXPF9ECVNDQTDQITIQBSTNWJPXSHWEMHSDYHOEZT9CMMRKOIFRZPSJVDBZGJOYMXM9KPJAPY",
"address": "LZK9VJPEJNKHKNADMKYIQVBLWRW9YEXBDPGSYMONHFGVXDHQ9FRLPDPCCHNYAJRCQSJWKWHBFHKYNPCHA",
"info": "Updated through Express Server"
}


###

POST http://localhost:5000/addAddress/
Content-Type: application/json

{
    "seed":"VLLPIQLDNUXPF9ECVNDQTDQITIQBSTNWJPXSHWEMHSDYHOEZT9CMMRKOIFRZPSJVDBZGJOYMXM9KPJAPY",
    "deviceNum": 5,
    "secLevel": 3,
    "id": "IDalpha",
    "password": "PASSWORD",
    "info": "HJHJFJGHFHGFHJ"
}


###

GET https://thetamiddleware.herokuapp.com/getSeed/Username2&Password2


###
GET http://localhost:5000/getAllSeeds/Admin_ID&Admin_Password

###
GET http://localhost:5000/getSeed/Username2&Password2

###
GET http://localhost:5000/forgotPassword/MBNDML9YVMXWKOMQZKYNJZQQRIQUQYLSNNDLSHCEAKKDJYHBPEWXBNXNXWOGQTHYUCBPPECYHVQFTZFOQ

###
GET http://localhost:5000/getTx/JKDXTRKXTILUCZCYERXMZCXKGBQWDIZYLLWFYKCYAMAVBXBAC9OKBVQVLRXHATUVDSNMVJK9IYHTA9999

###
GET http://localhost:5000/getHash/LZK9VJPEJNKHKNADMKYIQVBLWRW9YEXBDPGSYMONHFGVXDHQ9FRLPDPCCHNYAJRCQSJWKWHBFHKYNPCHA&21:42:22/28-8-2020

###
GET http://localhost:5000/getAllAddresses/VLLPIQLDNUXPF9ECVNDQTDQITIQBSTNWJPXSHWEMHSDYHOEZT9CMMRKOIFRZPSJVDBZGJOYMXM9KPJAPY

###
GET http://localhost:5000/getAllHash/LZK9VJPEJNKHKNADMKYIQVBLWRW9YEXBDPGSYMONHFGVXDHQ9FRLPDPCCHNYAJRCQSJWKWHBFHKYNPCHA&28-8-2020

###
GET http://localhost:5000/getLastTx/DHYBATJDVKBNRJRTS9CILIJRLEOVHFKNHBMTDRGKQAI9DFWMBJEJDIXHROLLODCMENPSHNXFHLWNDHWMZ

###
GET http://localhost:5000/getMAM/MBNDML9YVMXWKOMQZKYNJZQQRIQUQYLSNNDLSHCEAKKDJYHBPEWXBNXNXWOGQTHYUCBPPECYHVQFTZFOQ&NTWSWV9CBWVKZXKLWSOHFLCJTDWIAMVSYRD9DFDXWJWFBVPWYUYDJQDOOLEWLPOAPHR9CHQKTMEOYRKDC