POST https://thetamiddleware.herokuapp.com/addSeed/
Content-Type: application/json

{
"id": "IDalpha",
"pass": "PASSWORD",
"info": "HJHJFJGHFHGFHJ"
}

###
POST https://thetamiddleware.herokuapp.com/sendTx/
Content-Type: application/json

{
"seed": "MBNDML9YVMXWKOMQZKYNJZQQRIQUQYLSNNDLSHCEAKKDJYHBPEWXBNXNXWOGQTHYUCBPPECYHVQFTZFOQ",
"address": "NTWSWV9CBWVKZXKLWSOHFLCJTDWIAMVSYRD9DFDXWJWFBVPWYUYDJQDOOLEWLPOAPHR9CHQKTMEOYRKDC",
"msg": {
    "HR":"Hello",
    "BP": "Hello",
    "SpO2":"Hello"
}
}

###
POST https://thetamiddleware.herokuapp.com/updateStreamRoot/
Content-Type: application/json

{
"seed": "MBNDML9YVMXWKOMQZKYNJZQQRIQUQYLSNNDLSHCEAKKDJYHBPEWXBNXNXWOGQTHYUCBPPECYHVQFTZFOQ",
"address": "NTWSWV9CBWVKZXKLWSOHFLCJTDWIAMVSYRD9DFDXWJWFBVPWYUYDJQDOOLEWLPOAPHR9CHQKTMEOYRKDC",
"root": "ABCP9PLIRSUZKNYKMKPFTTLUSERLSKUSMMKJW9BGVOAHPAMDXDYQZAKDTKZLTHUBZBZXQNFCSUSVPATS9U"
}


###

POST https://thetamiddleware.herokuapp.com/addAddress/
Content-Type: application/json

{
    "seed":"VLLPIQLDNUXPF9ECVNDQTDQITIQBSTNWJPXSHWEMHSDYHOEZT9CMMRKOIFRZPSJVDBZGJOYMXM9KPJAPY",
    "deviceNum": 5,
    "secLevel": 3,
    "id": "IDalpha",
    "password": "PASSWORD",
    "info": "HJHJFJGHFHGFHJ"
}


###

GET https://thetamiddleware.herokuapp.com/getSeed/Username2&Password2


###
GET https://thetamiddleware.herokuapp.com/getAllSeeds/Admin_ID&Admin_Password

###
GET https://thetamiddleware.herokuapp.com/getSeed/Username2&Password2

###
GET https://thetamiddleware.herokuapp.com/forgotPassword/MBNDML9YVMXWKOMQZKYNJZQQRIQUQYLSNNDLSHCEAKKDJYHBPEWXBNXNXWOGQTHYUCBPPECYHVQFTZFOQ

###
GET https://thetamiddleware.herokuapp.com/getTx/JKDXTRKXTILUCZCYERXMZCXKGBQWDIZYLLWFYKCYAMAVBXBAC9OKBVQVLRXHATUVDSNMVJK9IYHTA9999

###
GET https://thetamiddleware.herokuapp.com/getHash/LZK9VJPEJNKHKNADMKYIQVBLWRW9YEXBDPGSYMONHFGVXDHQ9FRLPDPCCHNYAJRCQSJWKWHBFHKYNPCHA&21:42:22/28-8-2020

###
GET https://thetamiddleware.herokuapp.com/getAllAddresses/MBNDML9YVMXWKOMQZKYNJZQQRIQUQYLSNNDLSHCEAKKDJYHBPEWXBNXNXWOGQTHYUCBPPECYHVQFTZFOQ

###
GET https://thetamiddleware.herokuapp.com/getAllHash/NTWSWV9CBWVKZXKLWSOHFLCJTDWIAMVSYRD9DFDXWJWFBVPWYUYDJQDOOLEWLPOAPHR9CHQKTMEOYRKDC&0&prescription

###
GET https://thetamiddleware.herokuapp.com/getLastTx/TWAHITQOTATJPIBSSWPON9ISYOOZJCWWUOEEASVZMTWKCKSWKQSDMUTGOFO9JBEYWJGOVBCIS9BJR9HFD

###
GET https://thetamiddleware.herokuapp.com/getMAM/MBNDML9YVMXWKOMQZKYNJZQQRIQUQYLSNNDLSHCEAKKDJYHBPEWXBNXNXWOGQTHYUCBPPECYHVQFTZFOQ&NTWSWV9CBWVKZXKLWSOHFLCJTDWIAMVSYRD9DFDXWJWFBVPWYUYDJQDOOLEWLPOAPHR9CHQKTMEOYRKDC